"""Tests for the rule exporter write-side behavior."""

from pathlib import Path

import pytest

from afterpaths.exporters.base import (
    AUTO_END,
    AUTO_START,
    MANUAL_END,
    MANUAL_HELPER_LINE,
    MANUAL_START,
    Rule,
    extract_auto_section,
    extract_manual_section,
    has_unmanaged_content,
)
from afterpaths.exporters.claude import ClaudeExporter
from afterpaths.exporters.cursor import CursorExporter


# -- fixtures ----------------------------------------------------------------


def _rule(category: str, title: str = "Test rule", content: str = "Do the thing") -> Rule:
    return Rule(
        category=category,
        title=title,
        content=content,
        source_sessions=["abc12345"],
    )


@pytest.fixture
def gotchas_rules():
    return {"gotchas": [_rule("gotchas", "Sample", "Watch out for X")]}


@pytest.fixture
def all_category_rules():
    return {
        "dead_ends": [_rule("dead_ends", "DE", "don't X")],
        "decisions": [_rule("decisions", "D", "use Y")],
        "gotchas": [_rule("gotchas", "G", "watch for Z")],
        "patterns": [_rule("patterns", "P", "prefer Q")],
    }


# -- base helpers ------------------------------------------------------------


def test_extract_manual_section_returns_none_when_absent():
    assert extract_manual_section("# Title\n\nnothing here") is None


def test_extract_manual_section_returns_inner_content():
    content = f"# t\n\n{MANUAL_START}\nhello\nworld\n{MANUAL_END}\n"
    assert extract_manual_section(content) == "hello\nworld"


def test_extract_auto_section_returns_inner_content():
    content = f"{AUTO_START}\nbody\n{AUTO_END}"
    assert extract_auto_section(content) == "body"


def test_has_unmanaged_content_true_for_extra_prose():
    content = (
        "# Gotchas\n\n"
        "This is a hand-written note that is not in any markers.\n\n"
        f"{AUTO_START}\n"
        "## Rules\n\n"
        "- **X**: y\n  _Source: abc_\n\n"
        "---\n_Generated by afterpaths_\n"
        f"{AUTO_END}\n"
    )
    assert has_unmanaged_content(content) is True


def test_has_unmanaged_content_false_for_legacy_boilerplate_only():
    content = (
        "# Gotchas\n\n"
        "> Auto-generated by `afterpaths distill` | Updated: 2026-04-21 10:00\n"
        "> Sources: 1 session(s)\n\n"
        "## Rules\n\n"
        "- **X**: y\n  _Source: abc_\n\n"
        "---\n_Generated by afterpaths_\n"
    )
    assert has_unmanaged_content(content) is False


def test_has_unmanaged_content_false_for_markers_with_empty_manual():
    content = (
        "# Gotchas\n\n"
        f"{MANUAL_START}\n{MANUAL_HELPER_LINE}\n{MANUAL_END}\n\n"
        f"{AUTO_START}\n"
        "> Auto-generated by `afterpaths distill` | Updated: 2026-04-21 10:00\n"
        "> Sources: 1 session(s)\n\n"
        "## Rules\n\n"
        "- **X**: y\n  _Source: abc_\n\n"
        "---\n_Generated by afterpaths_\n"
        f"{AUTO_END}\n"
    )
    assert has_unmanaged_content(content) is False


def test_has_unmanaged_content_ignores_manual_body():
    content = (
        "# Gotchas\n\n"
        f"{MANUAL_START}\n"
        "This is a totally free-form paragraph the user wrote. "
        "It contains all kinds of non-boilerplate text, bullet points, random prose.\n"
        "- not a rule line\n"
        f"{MANUAL_END}\n\n"
        f"{AUTO_START}\n## Rules\n\n---\n_Generated by afterpaths_\n{AUTO_END}\n"
    )
    assert has_unmanaged_content(content) is False


def test_has_unmanaged_content_true_for_content_after_auto_end():
    content = (
        "# Gotchas\n\n"
        f"{AUTO_START}\n## Rules\n\n---\n_Generated by afterpaths_\n{AUTO_END}\n"
        "Stray content below the auto section.\n"
    )
    assert has_unmanaged_content(content) is True


# -- ClaudeExporter ----------------------------------------------------------


def test_claude_fresh_export_includes_markers_and_helper_line(tmp_path, gotchas_rules):
    exporter = ClaudeExporter()
    exporter.export(gotchas_rules, tmp_path)

    written = (tmp_path / ".claude" / "rules" / "gotchas.md").read_text()
    assert MANUAL_START in written
    assert MANUAL_END in written
    assert AUTO_START in written
    assert AUTO_END in written
    assert MANUAL_HELPER_LINE in written
    assert "- **Sample**: Watch out for X" in written


def test_claude_manual_content_survives_round_trip(tmp_path, gotchas_rules):
    exporter = ClaudeExporter()
    exporter.export(gotchas_rules, tmp_path)

    path = tmp_path / ".claude" / "rules" / "gotchas.md"
    original = path.read_text()
    manual_body = "These are my SCOTUS-probing methodology notes.\n- bullet 1\n- bullet 2"
    edited = original.replace(
        MANUAL_HELPER_LINE,
        manual_body,
    )
    path.write_text(edited)

    # Re-export with different rules
    new_rules = {"gotchas": [_rule("gotchas", "New", "different content")]}
    exporter.export(new_rules, tmp_path)

    final = path.read_text()
    assert manual_body in final
    assert "- **New**: different content" in final
    # The old rule must be gone
    assert "- **G**: watch for Z" not in final


def test_claude_legacy_file_with_only_boilerplate_is_not_flagged(tmp_path):
    rules_dir = tmp_path / ".claude" / "rules"
    rules_dir.mkdir(parents=True)
    legacy = rules_dir / "gotchas.md"
    legacy.write_text(
        "# Gotchas: Things to Watch For\n\n"
        "> Auto-generated by `afterpaths distill` | Updated: 2025-01-01 00:00\n"
        "> Sources: 1 session(s)\n\n"
        "## Rules\n\n"
        "- **Legacy rule**: do this\n  _Source: deadbeef_\n\n"
        "---\n_Generated by afterpaths_\n"
    )

    exporter = ClaudeExporter()
    assert exporter.check_unmanaged(tmp_path) == []


def test_claude_legacy_file_with_prose_is_flagged(tmp_path):
    rules_dir = tmp_path / ".claude" / "rules"
    rules_dir.mkdir(parents=True)
    legacy = rules_dir / "gotchas.md"
    legacy.write_text(
        "# Gotchas: Things to Watch For\n\n"
        "These are my hand-written notes that do not fit the rule format.\n"
        "They should never be overwritten.\n\n"
        "## Rules\n\n"
        "- **Legacy rule**: do this\n  _Source: deadbeef_\n"
    )

    exporter = ClaudeExporter()
    flagged = exporter.check_unmanaged(tmp_path)
    assert flagged == [legacy]


def test_claude_legacy_file_migrates_and_is_reported(tmp_path):
    rules_dir = tmp_path / ".claude" / "rules"
    rules_dir.mkdir(parents=True)
    legacy_path = rules_dir / "gotchas.md"
    legacy_path.write_text(
        "# Gotchas: Things to Watch For\n\n"
        "> Auto-generated by `afterpaths distill` | Updated: 2025-01-01 00:00\n"
        "> Sources: 1 session(s)\n\n"
        "## Rules\n\n"
        "- **Legacy rule**: do this\n  _Source: deadbeef_\n\n"
        "---\n_Generated by afterpaths_\n"
    )

    exporter = ClaudeExporter()
    rules = {"gotchas": [_rule("gotchas", "Fresh", "a new rule")]}
    result = exporter.export(rules, tmp_path)

    assert legacy_path in result.migrated_files
    final = legacy_path.read_text()
    assert MANUAL_START in final
    assert AUTO_START in final
    assert "- **Fresh**: a new rule" in final


def test_claude_load_existing_ignores_manual_section(tmp_path):
    rules_dir = tmp_path / ".claude" / "rules"
    rules_dir.mkdir(parents=True)
    path = rules_dir / "gotchas.md"
    path.write_text(
        "# Gotchas\n\n"
        f"{MANUAL_START}\n"
        "- **Manual rule**: should NOT be re-ingested\n  _Source: manualrule_\n"
        f"{MANUAL_END}\n\n"
        f"{AUTO_START}\n"
        "## Rules\n\n"
        "- **Auto rule**: should be re-ingested\n  _Source: abc12345_\n\n"
        "---\n_Generated by afterpaths_\n"
        f"{AUTO_END}\n"
    )

    exporter = ClaudeExporter()
    loaded = exporter.load_existing(tmp_path)

    assert "gotchas" in loaded
    titles = [r.title for r in loaded["gotchas"]]
    assert "Auto rule" in titles
    assert "Manual rule" not in titles


def test_claude_re_export_is_stable(tmp_path, gotchas_rules):
    """Two consecutive exports should produce an identical manual section."""
    exporter = ClaudeExporter()
    exporter.export(gotchas_rules, tmp_path)
    path = tmp_path / ".claude" / "rules" / "gotchas.md"
    manual_1 = extract_manual_section(path.read_text())

    exporter.export(gotchas_rules, tmp_path)
    manual_2 = extract_manual_section(path.read_text())

    assert manual_1 == manual_2


# -- CursorExporter ----------------------------------------------------------


def test_cursor_fresh_export_includes_markers(tmp_path, all_category_rules):
    (tmp_path / ".cursor").mkdir()  # so detect() is satisfied externally
    exporter = CursorExporter()
    exporter.export(all_category_rules, tmp_path)

    written = (tmp_path / ".cursor" / "rules" / "afterpaths-rules.mdc").read_text()
    assert MANUAL_START in written
    assert MANUAL_END in written
    assert AUTO_START in written
    assert AUTO_END in written
    assert "## Dead Ends" in written
    assert "## Patterns" in written


def test_cursor_manual_section_survives_round_trip(tmp_path, all_category_rules):
    (tmp_path / ".cursor").mkdir()
    exporter = CursorExporter()
    exporter.export(all_category_rules, tmp_path)

    path = tmp_path / ".cursor" / "rules" / "afterpaths-rules.mdc"
    original = path.read_text()
    manual_body = "Project-wide cursor notes that must not be lost."
    path.write_text(original.replace(MANUAL_HELPER_LINE, manual_body))

    # Change the rule set and re-export
    new_rules = {"gotchas": [_rule("gotchas", "Only one", "simpler now")]}
    exporter.export(new_rules, tmp_path)

    final = path.read_text()
    assert manual_body in final
    assert "- **Only one**: simpler now" in final


def test_cursor_legacy_file_with_prose_is_flagged(tmp_path):
    rules_dir = tmp_path / ".cursor" / "rules"
    rules_dir.mkdir(parents=True)
    legacy = rules_dir / "afterpaths-rules.mdc"
    legacy.write_text(
        "# Afterpaths: Extracted Rules\n\n"
        "A stray paragraph outside any markers or known boilerplate.\n\n"
        "## Gotchas\n\n"
        "- **Old**: content\n  _Source: abc_\n"
    )

    exporter = CursorExporter()
    flagged = exporter.check_unmanaged(tmp_path)
    assert flagged == [legacy]


def test_cursor_load_existing_ignores_manual_section(tmp_path):
    rules_dir = tmp_path / ".cursor" / "rules"
    rules_dir.mkdir(parents=True)
    path = rules_dir / "afterpaths-rules.mdc"
    path.write_text(
        "# Afterpaths: Extracted Rules\n\n"
        f"{MANUAL_START}\n"
        "## Gotchas\n\n"
        "- **Manual**: not distilled\n  _Source: hand0000_\n"
        f"{MANUAL_END}\n\n"
        f"{AUTO_START}\n"
        "## Gotchas\n\n"
        "- **Auto**: distilled\n  _Source: abc12345_\n\n"
        "---\n_Generated by afterpaths_\n"
        f"{AUTO_END}\n"
    )

    exporter = CursorExporter()
    loaded = exporter.load_existing(tmp_path)

    assert "gotchas" in loaded
    titles = [r.title for r in loaded["gotchas"]]
    assert "Auto" in titles
    assert "Manual" not in titles


# -- run_extract_rules integration (force flag) ------------------------------


def test_force_bypasses_unmanaged_check(tmp_path, monkeypatch, all_category_rules):
    """--force should skip the unmanaged check and overwrite."""
    from afterpaths import rules as rules_mod

    # Seed an unmanaged legacy file
    rules_dir = tmp_path / ".claude" / "rules"
    rules_dir.mkdir(parents=True)
    path = rules_dir / "gotchas.md"
    path.write_text(
        "# Gotchas\n\nUnmanaged prose that would normally block the run.\n"
    )

    # Stub out summary loading and extraction so the function runs end-to-end
    # without touching the filesystem's summary store or the LLM.
    monkeypatch.setattr(
        rules_mod,
        "load_recent_summaries",
        lambda days: [("sess1", "content", None)],
    )
    monkeypatch.setattr(
        rules_mod,
        "extract_rules_from_summaries",
        lambda summaries: all_category_rules,
    )
    monkeypatch.setattr(
        rules_mod, "merge_rules", lambda existing, new: new
    )
    monkeypatch.setattr(rules_mod, "update_rules_metadata", lambda ids: None)
    monkeypatch.setattr(rules_mod, "get_rules_metadata", lambda: {})

    # Without --force: aborts.
    result = rules_mod.run_extract_rules(
        days=7, target="claude", project_root=tmp_path, force=False
    )
    assert result.status == "unmanaged_content"
    assert path in result.unmanaged_files
    # File still has its original unmanaged prose
    assert "Unmanaged prose" in path.read_text()

    # With --force: succeeds.
    result = rules_mod.run_extract_rules(
        days=7, target="claude", project_root=tmp_path, force=True
    )
    assert result.status == "success"
    final = path.read_text()
    assert "Unmanaged prose" not in final
    assert MANUAL_START in final
    assert AUTO_START in final
