"""Base class for rule exporters."""

import re
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path


MANUAL_START = "<!-- afterpaths:manual:start -->"
MANUAL_END = "<!-- afterpaths:manual:end -->"
AUTO_START = "<!-- afterpaths:auto:start -->"
AUTO_END = "<!-- afterpaths:auto:end -->"

MANUAL_HELPER_LINE = (
    "_Add project-specific notes here — preserved across `ap rules` runs._"
)
AUTO_WARNING_COMMENT = (
    "<!-- Content below is regenerated by `ap rules`. "
    "To preserve edits, use the manual section above. -->"
)

# Rule line pattern: - **Title**: content\n  _Source: X_
RULE_LINE_PATTERN = re.compile(
    r'-\s+\*\*([^*]+)\*\*:\s*(.+?)\n\s+_Source:\s*([^_]+)_',
    re.MULTILINE,
)

# Lines that are recognized as boilerplate and are therefore safe to strip
# when deciding whether a file has unmanaged content. Everything else in the
# pre-manual zone or inside the auto zone (once rule lines are stripped) is
# treated as unmanaged.
_BOILERPLATE_LINE_PATTERNS = [
    re.compile(r'^\s*$'),                                   # blank
    re.compile(r'^#\s'),                                    # any H1 heading
    re.compile(r'^##\s'),                                   # any H2 heading
    re.compile(r'^>\s*Auto-generated by\s+`afterpaths'),    # meta line 1
    re.compile(r'^>\s*Sources:\s*\d+\s+session'),           # claude meta line 2
    re.compile(r'^>\s*\d+\s+rules?\s+from\s+\d+\s+session'),  # cursor meta line 2
    re.compile(r'^---\s*$'),                                # horizontal rule
    re.compile(r'^_Generated by afterpaths_\s*$'),          # footer
    re.compile(r'^\s*<!--.*-->\s*$'),                       # any single-line html comment
]


@dataclass
class Rule:
    """A single extracted rule."""

    category: str  # dead_ends, decisions, gotchas, patterns
    title: str
    content: str
    source_sessions: list[str] = field(default_factory=list)
    confidence: str = "high"  # high, medium
    extracted_at: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class ExportResult:
    """Result of an export operation."""

    target: str
    files_written: list[Path]
    rules_count: int
    success: bool = True
    error: str | None = None
    migrated_files: list[Path] = field(default_factory=list)


def extract_manual_section(content: str) -> str | None:
    """Return the text between manual markers, or None if markers are absent.

    An empty manual section (no content between markers) returns "".
    """
    start = content.find(MANUAL_START)
    if start == -1:
        return None
    end = content.find(MANUAL_END, start + len(MANUAL_START))
    if end == -1:
        return None
    inner = content[start + len(MANUAL_START):end]
    # Strip one leading and one trailing newline so the re-wrapped output
    # doesn't accumulate blank lines across runs.
    if inner.startswith("\n"):
        inner = inner[1:]
    if inner.endswith("\n"):
        inner = inner[:-1]
    return inner


def extract_auto_section(content: str) -> str | None:
    """Return the text between auto markers, or None if markers are absent."""
    start = content.find(AUTO_START)
    if start == -1:
        return None
    end = content.find(AUTO_END, start + len(AUTO_START))
    if end == -1:
        return None
    inner = content[start + len(AUTO_START):end]
    if inner.startswith("\n"):
        inner = inner[1:]
    if inner.endswith("\n"):
        inner = inner[:-1]
    return inner


def _strip_rule_blocks(text: str) -> str:
    """Remove rule-line blocks (title + source line) from text."""
    return RULE_LINE_PATTERN.sub("", text)


def _is_all_boilerplate(text: str) -> bool:
    """Return True if every remaining line matches a recognized boilerplate pattern."""
    for line in text.splitlines():
        if not any(pat.search(line) for pat in _BOILERPLATE_LINE_PATTERNS):
            return False
    return True


def has_unmanaged_content(content: str) -> bool:
    """Return True if the file contains content that would be silently overwritten.

    Checks three zones:
    - Pre-manual zone (everything before manual:start, or whole file if markers absent)
    - Auto zone (inside auto markers, after stripping rule blocks)
    - Post-auto zone (anything after auto:end)

    Manual zone is never inspected. Content counts as "unmanaged" if, after
    removing recognized boilerplate and rule-line blocks, anything remains.
    """
    manual_start_idx = content.find(MANUAL_START)
    manual_end_idx = content.find(MANUAL_END, manual_start_idx + 1) if manual_start_idx != -1 else -1
    auto_start_idx = content.find(AUTO_START)
    auto_end_idx = content.find(AUTO_END, auto_start_idx + 1) if auto_start_idx != -1 else -1

    # Zone 1: pre-manual (or pre-auto if manual missing, or whole file if both missing)
    if manual_start_idx != -1:
        pre_zone = content[:manual_start_idx]
    elif auto_start_idx != -1:
        pre_zone = content[:auto_start_idx]
    else:
        pre_zone = content

    if not _is_all_boilerplate(_strip_rule_blocks(pre_zone)):
        return True

    # Zone 2: between manual:end and auto:start (if both present)
    if manual_end_idx != -1 and auto_start_idx != -1 and manual_end_idx < auto_start_idx:
        between = content[manual_end_idx + len(MANUAL_END):auto_start_idx]
        if not _is_all_boilerplate(_strip_rule_blocks(between)):
            return True

    # Zone 3: inside auto section — rules + boilerplate only
    if auto_start_idx != -1 and auto_end_idx != -1:
        auto_inner = content[auto_start_idx + len(AUTO_START):auto_end_idx]
        if not _is_all_boilerplate(_strip_rule_blocks(auto_inner)):
            return True

    # Zone 4: post-auto (anything after auto:end, except the final newline)
    if auto_end_idx != -1:
        tail = content[auto_end_idx + len(AUTO_END):]
        if not _is_all_boilerplate(tail):
            return True

    return False


def wrap_with_markers(header: str, manual_content: str | None, auto_body: str) -> str:
    """Assemble final file content: header + manual section + auto section.

    If manual_content is None, inserts an empty manual section with the visible
    helper line. If manual_content is an empty string, also inserts the helper
    line (treating "empty markers" identically to "no markers found"). If
    manual_content has text, it is preserved verbatim — the helper line is
    omitted so the user can curate freely.
    """
    if manual_content is None or manual_content.strip() == "":
        manual_block = f"{MANUAL_START}\n{MANUAL_HELPER_LINE}\n{MANUAL_END}"
    else:
        manual_block = f"{MANUAL_START}\n{manual_content}\n{MANUAL_END}"

    auto_block = f"{AUTO_START}\n{AUTO_WARNING_COMMENT}\n\n{auto_body}\n{AUTO_END}"

    return f"{header}\n\n{manual_block}\n\n{auto_block}\n"


class RuleExporter(ABC):
    """Abstract base class for rule exporters.

    Each exporter handles a specific AI coding assistant's rule format.
    """

    name: str  # e.g., "claude", "cursor"
    description: str  # Human-readable description

    @abstractmethod
    def detect(self, project_root: Path) -> bool:
        """Return True if this target should be used for this project.

        Detection can be based on:
        - Presence of config files (e.g., .cursor/ directory)
        - Explicit user configuration
        - Default behavior
        """
        pass

    @abstractmethod
    def export(self, rules: dict[str, list[Rule]], project_root: Path) -> ExportResult:
        """Write rules to the target format.

        Args:
            rules: Dict mapping category names to lists of Rule objects
            project_root: Root directory of the project

        Returns:
            ExportResult with details of what was written
        """
        pass

    @abstractmethod
    def load_existing(self, project_root: Path) -> dict[str, list[Rule]]:
        """Load existing rules from the target for merging.

        Returns empty dict if no existing rules found. Implementations must
        only parse content inside the auto markers so that manually-authored
        rules aren't re-ingested as if they were distilled.
        """
        pass

    def check_unmanaged(self, project_root: Path) -> list[Path]:
        """Return paths whose existing content would be overwritten.

        Default implementation checks every file in get_output_paths() using
        has_unmanaged_content(). Exporters can override for custom behavior.
        """
        unmanaged = []
        for path in self.get_output_paths(project_root):
            if not path.exists():
                continue
            try:
                content = path.read_text()
            except OSError:
                continue
            if has_unmanaged_content(content):
                unmanaged.append(path)
        return unmanaged

    def get_output_paths(self, project_root: Path) -> list[Path]:
        """Return the paths where this exporter writes files.

        Useful for dry-run and status display.
        """
        return []
