"""Claude Code exporter - writes to .claude/rules/ directory."""

from datetime import datetime
from pathlib import Path

from .base import (
    AUTO_END,
    AUTO_START,
    ExportResult,
    RULE_LINE_PATTERN,
    Rule,
    RuleExporter,
    extract_auto_section,
    extract_manual_section,
    wrap_with_markers,
)

# Category display names and filenames
CATEGORIES = {
    "dead_ends": ("Dead Ends: What Not to Try", "dead-ends.md"),
    "decisions": ("Decisions: Architectural Choices", "decisions.md"),
    "gotchas": ("Gotchas: Things to Watch For", "gotchas.md"),
    "patterns": ("Patterns: Techniques That Work", "patterns.md"),
}


class ClaudeExporter(RuleExporter):
    """Exports rules to .claude/rules/ for Claude Code.

    Creates separate markdown files per category that Claude Code
    automatically loads into context.
    """

    name = "claude"
    description = "Claude Code (.claude/rules/)"

    def detect(self, project_root: Path) -> bool:
        """Always available - Claude Code is our primary target."""
        return True

    def get_output_paths(self, project_root: Path) -> list[Path]:
        """Return paths for all category files."""
        rules_dir = project_root / ".claude" / "rules"
        return [rules_dir / filename for _, filename in CATEGORIES.values()]

    def export(self, rules: dict[str, list[Rule]], project_root: Path) -> ExportResult:
        """Write rules to .claude/rules/*.md files."""
        rules_dir = project_root / ".claude" / "rules"
        rules_dir.mkdir(parents=True, exist_ok=True)

        files_written: list[Path] = []
        migrated_files: list[Path] = []
        total_rules = 0

        for category, (title, filename) in CATEGORIES.items():
            category_rules = rules.get(category, [])
            if not category_rules:
                continue

            file_path = rules_dir / filename

            manual_content: str | None = None
            had_markers = False
            if file_path.exists():
                existing = file_path.read_text()
                manual_content = extract_manual_section(existing)
                had_markers = manual_content is not None or AUTO_START in existing
                if not had_markers:
                    migrated_files.append(file_path)

            header = f"# {title}"
            auto_body = self._format_auto_body(category_rules)
            content = wrap_with_markers(header, manual_content, auto_body)

            file_path.write_text(content)
            files_written.append(file_path)
            total_rules += len(category_rules)

        return ExportResult(
            target=self.name,
            files_written=files_written,
            rules_count=total_rules,
            migrated_files=migrated_files,
        )

    def load_existing(self, project_root: Path) -> dict[str, list[Rule]]:
        """Load existing rules from .claude/rules/ files.

        Only parses content inside the auto markers. Legacy files (written
        by v0.2.0, no markers) are still parsed in full for one upgrade.
        """
        rules_dir = project_root / ".claude" / "rules"
        if not rules_dir.exists():
            return {}

        existing: dict[str, list[Rule]] = {}

        for category, (_, filename) in CATEGORIES.items():
            file_path = rules_dir / filename
            if not file_path.exists():
                continue

            content = file_path.read_text()
            auto_section = extract_auto_section(content)
            # For legacy files without markers, fall back to the full file
            # so existing rules aren't lost on the migration run.
            scan_text = auto_section if auto_section is not None else content

            parsed = self._parse_rules_text(scan_text, category)
            if parsed:
                existing[category] = parsed

        return existing

    def _format_auto_body(self, rules: list[Rule]) -> str:
        """Format the auto-regenerated body (meta lines + rules + footer)."""
        all_sessions: set[str] = set()
        for rule in rules:
            all_sessions.update(rule.source_sessions)

        lines = [
            f"> Auto-generated by `afterpaths distill` | Updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            f"> Sources: {len(all_sessions)} session(s)",
            "",
            "## Rules",
            "",
        ]

        for rule in rules:
            sources = rule.source_sessions or ["unknown"]
            source_str = ", ".join(s[:8] for s in sources[:3])
            if len(sources) > 3:
                source_str += f" (+{len(sources) - 3} more)"

            lines.append(f"- **{rule.title}**: {rule.content}")
            lines.append(f"  _Source: {source_str}_")
            lines.append("")

        lines.extend([
            "---",
            "_Generated by afterpaths_",
        ])

        return "\n".join(lines)

    def _parse_rules_text(self, text: str, category: str) -> list[Rule]:
        """Parse rules from a block of text using the rule-line regex."""
        rules: list[Rule] = []

        for match in RULE_LINE_PATTERN.finditer(text):
            title = match.group(1).strip()
            rule_content = match.group(2).strip()
            source_str = match.group(3).strip()

            sources: list[str] = []
            source_parts = source_str.replace("(+", "").replace("more)", "").split(",")
            for part in source_parts:
                part = part.strip()
                if part and not part.isdigit():
                    sources.append(part)

            rules.append(Rule(
                category=category,
                title=title,
                content=rule_content,
                source_sessions=sources,
            ))

        return rules
