"""Cursor exporter - writes to .cursor/rules/ directory."""

import re
from datetime import datetime
from pathlib import Path

from .base import (
    AUTO_START,
    ExportResult,
    RULE_LINE_PATTERN,
    Rule,
    RuleExporter,
    extract_auto_section,
    extract_manual_section,
    wrap_with_markers,
)

# Category display names for Cursor format
CATEGORY_TITLES = {
    "dead_ends": "Dead Ends",
    "decisions": "Decisions",
    "gotchas": "Gotchas",
    "patterns": "Patterns",
}


class CursorExporter(RuleExporter):
    """Exports rules to .cursor/rules/ for Cursor IDE.

    Creates a single consolidated file that Cursor auto-loads.
    Uses .mdc extension (Cursor's markdown format).
    """

    name = "cursor"
    description = "Cursor IDE (.cursor/rules/)"

    def detect(self, project_root: Path) -> bool:
        """Detect if Cursor is being used (has .cursor directory)."""
        return (project_root / ".cursor").exists()

    def get_output_paths(self, project_root: Path) -> list[Path]:
        """Return path to the rules file."""
        return [project_root / ".cursor" / "rules" / "afterpaths-rules.mdc"]

    def export(self, rules: dict[str, list[Rule]], project_root: Path) -> ExportResult:
        """Write rules to .cursor/rules/afterpaths-rules.mdc."""
        rules_dir = project_root / ".cursor" / "rules"
        rules_dir.mkdir(parents=True, exist_ok=True)

        file_path = rules_dir / "afterpaths-rules.mdc"

        manual_content: str | None = None
        migrated_files: list[Path] = []
        if file_path.exists():
            existing = file_path.read_text()
            manual_content = extract_manual_section(existing)
            had_markers = manual_content is not None or AUTO_START in existing
            if not had_markers:
                migrated_files.append(file_path)

        header = "# Afterpaths: Extracted Rules"
        auto_body = self._format_auto_body(rules)
        content = wrap_with_markers(header, manual_content, auto_body)

        file_path.write_text(content)

        total_rules = sum(len(r) for r in rules.values())

        return ExportResult(
            target=self.name,
            files_written=[file_path],
            rules_count=total_rules,
            migrated_files=migrated_files,
        )

    def load_existing(self, project_root: Path) -> dict[str, list[Rule]]:
        """Load existing rules from the auto section of the consolidated file."""
        file_path = project_root / ".cursor" / "rules" / "afterpaths-rules.mdc"
        if not file_path.exists():
            return {}

        content = file_path.read_text()
        auto_section = extract_auto_section(content)
        scan_text = auto_section if auto_section is not None else content

        return self._parse_rules_text(scan_text)

    def _format_auto_body(self, rules: dict[str, list[Rule]]) -> str:
        """Format the auto-regenerated body for the consolidated file."""
        all_sessions: set[str] = set()
        total_rules = 0
        for category_rules in rules.values():
            for rule in category_rules:
                all_sessions.update(rule.source_sessions)
                total_rules += 1

        lines = [
            f"> Auto-generated by `afterpaths distill` | Updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            f"> {total_rules} rules from {len(all_sessions)} session(s)",
            "",
        ]

        for category, title in CATEGORY_TITLES.items():
            category_rules = rules.get(category, [])
            if not category_rules:
                continue

            lines.append(f"## {title}")
            lines.append("")

            for rule in category_rules:
                sources = rule.source_sessions or ["unknown"]
                source_str = ", ".join(s[:8] for s in sources[:3])
                if len(sources) > 3:
                    source_str += f" (+{len(sources) - 3} more)"

                lines.append(f"- **{rule.title}**: {rule.content}")
                lines.append(f"  _Source: {source_str}_")
                lines.append("")

        lines.extend([
            "---",
            "_Generated by afterpaths_",
        ])

        return "\n".join(lines)

    def _parse_rules_text(self, text: str) -> dict[str, list[Rule]]:
        """Parse rules from consolidated-file text, grouped by category."""
        rules: dict[str, list[Rule]] = {}
        header_to_category = {v.lower(): k for k, v in CATEGORY_TITLES.items()}

        for match in RULE_LINE_PATTERN.finditer(text):
            title = match.group(1).strip()
            rule_content = match.group(2).strip()
            source_str = match.group(3).strip()

            pos = match.start()
            category = self._find_category_at_position(text, pos, header_to_category)
            if not category:
                continue

            sources: list[str] = []
            source_parts = source_str.replace("(+", "").replace("more)", "").split(",")
            for part in source_parts:
                part = part.strip()
                if part and not part.isdigit():
                    sources.append(part)

            rules.setdefault(category, []).append(Rule(
                category=category,
                title=title,
                content=rule_content,
                source_sessions=sources,
            ))

        return rules

    def _find_category_at_position(
        self, content: str, pos: int, header_map: dict[str, str]
    ) -> str | None:
        """Find which category a position in the file belongs to."""
        last_category = None
        for match in re.finditer(r'^## (.+)$', content[:pos], re.MULTILINE):
            header = match.group(1).strip().lower()
            if header in header_map:
                last_category = header_map[header]
        return last_category
